name: Build Artifacts

on:
  pull_request:
    branches:
      - develop
      - main
    paths:
      - src/**
      - .github/workflows/**      
  push:
    branches:
      - develop
      - main
    paths:
      - src/**
      - .github/workflows/**      
jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        source-url: https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Setup .NET Core 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Restore solution
      working-directory: src
      run: dotnet restore
    - name: Build solution [Release]
      working-directory: src
      run: dotnet build --no-restore -c Release -p:VersionSuffix=$GITHUB_RUN_NUMBER
    - name: Build solution [Debug]
      working-directory: src
      run: dotnet build --no-restore -c Debug -p:VersionSuffix=$GITHUB_RUN_NUMBER
    - name: Test
      working-directory: src
      run: dotnet test --no-restore --no-build --configuration Debug -p:CollectCoverage=true
    - name: Pack solution [Release]
      working-directory: src
      run: dotnet pack --no-restore -c Release -p:VersionSuffix=$GITHUB_RUN_NUMBER -o out
    - uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: src/out/*
    - name: Upload coverage
      uses: codecov/codecov-action@v2
      with:
        files: src/.coverage/Epam.GraphQL.EntityFrameworkCore.Tests/coverage.opencover.xml,src/.coverage/Epam.GraphQL.Tests/coverage.opencover.xml
        verbose: true
        